### PR TITLE
Credential binding

### PR DESCRIPTION
**Pull request by crathjen**
This attempts to address the comments from @ptierno on https://github.com/jenkinsci/hashicorp-vault-plugin/pull/16

### CODE REVIEW

**Comment by crathjen** [comment]
Is there a process to initiate PR reviews?

**Comment by robloxrob** [comment]
This would be a great feature to have so I can get access to the VAULT_TOKEN for doing various Terraform actions.

**Comment by gswallow** [comment]
Are there plans for a new release following the merge of this feature?  I installed it by hand but this seems like a fairly major development to go untagged.

**Comment by justinsaliba** [comment]
@gswallow how did you install this by hand please? I'm still holding out for an official release for the time being, but just in case I might have to install a SNAPSHOT version in Jenkins if push comes to shove.

**Comment by gigyas** [comment]
Would be really helpful to get a release of this and the KV version 2 support

**Comment by gswallow** [comment]
@justinsaliba sorry just saw this!

Here you go:
```bash
git clone https://github.com/jenkinsci/hashicorp-vault-plugin.git
cd hashicorp-vault-plugin/
git fetch -fu origin refs/pull/20/head:PR-20
git reset --hard PR-20
mvn compile && mvn package
ls target/*.hpi
```

Jenkins's plugins manager has a way to install plugins directly from .hpi files.

**Comment by casz** [comment]
@gswallow @Jahsis Released in [v2.3.0](https://github.com/jenkinsci/hashicorp-vault-plugin/releases/tag/hashicorp-vault-plugin-2.3.0)

**Pull request merged**
