### PR TITLE
Changed Vault login strategy to AppRole instead of Token.

### PR DESCRIPTION
**Pull request by schmitzhermes**
AppRole is the far superior auth backend. It is way more suitable for applications like Jenkins.
We now need to supply a RoleID and an SecretID. Based on this credentials we can obtain a token from Vault.
This token is only valid for a couple of minutes then.

We can restrict the RoleID/SecretID-tuple to have a ttl (and all this other stuff). What I recommend, though, is restricting the usage of the AppRole backend via `bound_cidr_list`. This way the RoleID/SecretID-tuple can only be exchanged for a valid access token when the request comes from a certain IP range.

It is based on #3.

### CODE REVIEW

**Comment by tobilarscheid** [comment]
From the [vault documentation](https://www.vaultproject.io/docs/auth/approle.html):
> But for servers the AppRole backend is the recommended choice.
> This backend is oriented to automated workflows, and is the successor to the App-ID backend.

I therefore vote for this PR.

**Comment by schmitzhermes** [comment]
This is going to be a breaking API change.

**Comment by ptierno** [comment]
@schmitzhermes idieally what i would like to see (especially since this will be a 2.0 release and we can implement breaking changes) is an option on how jenkins should auth to vault, whether it be approle, jenkins credential, or something like suggested in [JENKINS-37713](issues.jenkins-ci.org/browse/JENKINS-37713). If you have a compelling argument to use strictly approle i am open to considering it though.

**Comment by tobilarscheid** [comment]
Hi @ptierno, my personal understanding of the Vault documentation is that for automated workflows only the AppRole mode should be used. If people would really want to use a token, they could stay with release 1.3 of the plugin - I think allowing for self constructed token refreshment mechanisms like in JENKINS-37713 is not a good signal...

**Comment by schmitzhermes** [comment]
closed in favor of #6

**Pull request closed without merging**
