### PR TITLE
Fix ssh user key binding 

### PR DESCRIPTION
**Pull request by emelianrus**
fix JENKINS-63034

### CODE REVIEW

**Comment by jetersen** [comment]
link to see current commit author: https://github.com/jenkinsci/hashicorp-vault-plugin/commit/058ee271cfea1aaec632760f58d2a32cf38a4a1f.patch

@emelianrus 
You might want to set up an email alias on your GitHub account 🥇
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

Or look into fixing your git user.email config 😅  
https://help.github.com/articles/setting-your-commit-email-address-in-git
then you would need to amend your commits: https://stackoverflow.com/a/3042512
after changing author

to get proper credit for your commits 🏆

**Review by jetersen — APPROVED** [review]
LGTM apart from commit author not associated

**Comment by emelianrus** [comment]
> LGTM apart from commit author not associated

missed that, thanks

**Comment by jetersen** [comment]
Seems committer is still stuck. Might want to redo the commit 😅

**Comment by emelianrus** [comment]
> Seems committer is still stuck. Might want to redo the commit 😅

ok, all good, commit does not belong to any branch, let it be :) 
could be merged, if you don't have any concerns

**Pull request merged**
