### PR TITLE
setup snapshots so that credentials work on agents

### PR DESCRIPTION
**Pull request by jetersen**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jamesrobson-secondmind** [comment]
Do you need some assistance with this? I'm not very familiar with plugin internals so I'm not sure how this is intended to work, but if you can give me some direction I can get some time to work on it though I can't guarantee I'll be able to get it working.

**Comment by jetersen** [comment]
@jamesrobson-secondmind That would be appreciated.

Problem is I started adding other improvements that made the test failure occur.

You should be able to draw inspiration from https://github.com/jenkinsci/azure-keyvault-plugin/tree/master/src/main/java/org/jenkinsci/plugins/azurekeyvaultplugin/credentials/usernamepassword

**Comment by jamesrobson-secondmind** [comment]
I have a branch that 'works', the tests are all passing and I can use it on my test instance to retrieve credentials: https://github.com/jamesrobson-secondmind/hashicorp-vault-plugin/tree/use-snapshots
I had to make some changes such as not using lambdas as they can't be serialised and jenkins will refuse to run if you try. I've also taken out the use of the `ItemGroup` that was the original issue. It'd be good if you could have a look at this to make sure I haven't introduced any new issues.

Also, you didn't add a snapshot for `VaultFileCredential`, I'm not sure if that's an oversight or if that one is different and doesn't need one.

**Comment by jetersen** [comment]
@jamesrobson-secondmind feel free to open a pull request. Usually the easiest way to get it over the line 🙂

**Comment by jetersen** [comment]
fixed in #228

**Pull request closed without merging**
