### PR TITLE
Add GCP authentication backend

### PR DESCRIPTION
**Pull request by seanmalloy**
Jenkins masters running on a GCE instance can use this new vault authentication method which does not require storing any static secrets for authenticating to vault.

https://www.vaultproject.io/docs/auth/gcp.html#gce-login

### CODE REVIEW

**Comment by seanmalloy** [comment]
Missing code to get JWT from Google metadata. Have not tried to compile or test the code yet. Hoping to finish this up in the coming weeks.

**Comment by seanmalloy** [comment]
It compiles!

Next step is to actually test it.

**Comment by seanmalloy** [comment]
The code is working. Final count down ...

- [ ] update docs
- [ ] write some tests?
- [ ] get rid of audience field in Vault GCP cred

**Comment by seanmalloy** [comment]
@ptierno are you still the maintainer of this project? Would you be able to review this pull request?

**Comment by ptierno** [comment]
@seanmalloy Apologies for the delay. I am currently the sole maintainer and have been a little backed up. I will work on reviewing this and getting it merged between tonight and tomorrow.

**Comment by ptierno** [comment]
Thanks for the contribution, merging... Expect a release later today or during the weekend.

--
Peter Tierno
Senior DevOps Architect, Professional Services
E: peter.tierno@rackspace.com
W: www.rackspace.com

**Pull request merged**
