### PR TITLE
[JENKINS-58970] - allow setting engine version on `VaultConfiguration`

### PR DESCRIPTION
**Pull request by casz**
fixes #40

### CODE REVIEW

**Comment by kkalugerov** [comment]
As I can see from you PR the value of the field is `engineVersion ` but where exactly should be this value - in the wrapper like this - > `wrap([$class: 'VaultBuildWrapper', engineVersion: 1/2, vaultSecrets: secrets])` or in the secrets var like this -> `[path: 'secret/test', engineVersion: 1/2,  secretValues: [ `
Thanks in advance ! :)

**Comment by casz** [comment]
You can also set it higher up on the configuration object it is under the advanced button

**Comment by casz** [comment]
Here is an updated groovy snippet instead of using `wrap` you can use `withVault` same functionality just shorter to write.
engineVersion can be set from a secret, job, folder or global.
```groovy
node {
    // define the secrets and the env variables
    def secrets = [
        [path: 'secret/testing', engineVersion: 1, secretValues: [
            [envVar: 'testing', vaultKey: 'value_one'],
            [envVar: 'testing_again', vaultKey: 'value_two']]],
        [path: 'secret/another_test', engineVersion: 2, secretValues: [
            [vaultKey: 'another_test']]]
    ]

    // optional configuration, if you do not provide this the next higher configuration
    // (e.g. folder or global) will be used
    def configuration = [vaultUrl: 'http://my-very-other-vault-url.com',
                         vaultCredentialId: 'my-vault-cred-id'
                         engineVersion: 1]
    // inside this block your credentials will be available as env variables
    withVault([configuration: configuration, vaultSecrets: secrets]) {
        sh 'echo $testing'
        sh 'echo $testing_again'
        sh 'echo $another_test'
    }
}
```

**Comment by kkalugerov** [comment]
Thank you man !

**Comment by casz** [comment]
Your welcome 👍

**Pull request merged**
