### PR TITLE
Use try-with-resources when reading kubernetes service account token.

### PR DESCRIPTION
**Pull request by lhotrifork**
Hi,
We're using the plugin to inject git credentials into jobs. It works really well, except there seems to be a file descriptor leak somewhere in the code specifically to the kubernetes service account token.

I've created this issue https://issues.jenkins-ci.org/browse/JENKINS-61437

I think the culprit is `Files.lines` because as stated in the documentation https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#lines-java.nio.file.Path-java.nio.charset.Charset- 

>  If timely disposal of file system resources is required, the try-with-resources construct should be used to ensure that the stream's close method is invoked after the stream operations are completed.

All tests pass when running on my machine.

### CODE REVIEW

**Comment by lhotrifork** [comment]
Cool! I don't know if I can do something about the failing CI builds?

**Comment by jetersen** [comment]
Nah that's a known bug sadly 😓
https://github.com/actions/virtual-environments/issues/635

**Comment by fmotrifork** [comment]
Hi @jetersen,
This issue forces our Jenkins server to die every day.
Can we push it forward?

Best Regards.

**Comment by jetersen** [comment]
One bug hiding under another bug 😓

**Comment by jetersen** [comment]
third bug hiding under two 😓 Seems like ci.jenkins.io is foobar: https://issues.jenkins-ci.org/browse/INFRA-2566

**Pull request merged**
