### PR TITLE
Raise exception when access is denied instead of silently failing

### PR DESCRIPTION
**Pull request by bluesliverx**
This fixes #163 in the way asked for by @jetersen, but also adds a unit test to ensure correct behavior. I chose not to base it on the failIfNotFound flag since access denied shows a configuration issue that should be addressed immediately instead of "I have permissions, but it just doesn't exist" that failIfNotFound is for.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by bluesliverx** [comment]
I didn't see an existing issue except for the PR in #163, but we've run into this recently and it caused some serious issues and was VERY surprising to me as I just thought things were working, but it was actually silently failing.

**Comment by bluesliverx** [comment]
RETEST

**Comment by niclan** [comment]
Dear maintainers, this needs to be merged (unless you have a different change in place already)

**Comment by bluesliverx** [comment]
@jetersen I'm not sure if there are other maintainers here, but this PR has been open for nearly a year now. Any chance it could get a review/merge? We've been using it in our local fork with no issues in the last year.

**Comment by forest-code42** [comment]
I have raised a Jenkins JIRA ticket to please merge this PR https://issues.jenkins.io/browse/JENKINS-72324

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
released in [362.v8dfe4061f29e](https://github.com/jenkinsci/hashicorp-vault-plugin/releases/tag/362.v8dfe4061f29e)

**Pull request merged**
