### PR TITLE
JENKINS-58970 Set default engine version to 1 for backwards compat

### PR DESCRIPTION
**Pull request by bluesliverx**

### CODE REVIEW

**Comment by kkalugerov** [comment]
Guys are u going to merge this soon ?

**Comment by casz** [comment]
No, the default should be 2.

Please specify engine version in your pipeline / config

**Comment by bluesliverx** [comment]
@kkalugerov, please see the conversation at https://issues.jenkins-ci.org/browse/JENKINS-58970. I believe @casz is working on another way to solve this problem from what he said.

**Comment by casz** [comment]
I'll release #42 shortly 😓 Just wanted to clean up code style issues I kept fighting with.

**Pull request closed without merging**
