### PR TITLE
Approle credential binding

### PR DESCRIPTION
**Pull request by gotcha**
AppRoleCredentialsBinding exports VAULT_ADDR and VAULT_TOKEN variables to pipeline environment.

          withCredentials([[
             $class: 'VaultAppRoleCredentialBinding',
             credentialsId: 'approle',
             vaultAddr: 'http://vault:8200'
             ]]) {
             sh 'echo token=$VAULT_ADDR'
             sh 'echo token=$VAULT_TOKEN'
         }
 
The name of the exported variables can be chosen.
 
        withCredentials([[
            $class: 'VaultAppRoleCredentialBinding',
            addrVariable: 'VA',
            tokenVariable: 'VT',
            credentialsId: 'approle',
            vaultAddr: 'http://vault:8200'
            ]]) {
            sh 'echo token=$VT'
            sh 'echo addr=$VA'
        }

### CODE REVIEW

**Comment by gotcha** [comment]
Is there a way to get a review ?

**Comment by ptierno** [comment]
@gotcha I like the idea of this but i'm wondering if we can't get it to work with all instances of VaultCredential rather than writing a new binding for each VaultCredential class.

**Comment by gotcha** [comment]
Would be better to have a single class. Not sure I can manage it, I am not an experienced java coder

**Comment by hypePG** [comment]
is there any news on this, or a workaround for using AppRole Credentials in a pipeline?

**Pull request merged**
